deployment:
  tasks:
    - export DEPLOYPATH=/home/jrgparki/public_html/vis/
    - /bin/rm -rf $DEPLOYPATH/dist $DEPLOYPATH/static
    - /bin/cp -r dist $DEPLOYPATH
    - /bin/cp -r static $DEPLOYPATH
    - /bin/cp -r node_modules $DEPLOYPATH