deployment:
  tasks:
    # - npm install # should already be done
    - npm run buildProdCPanel
    - export DEPLOYPATH=/home/jrgparki/public_html/vis/
    - mkdir -p DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/dist $DEPLOYPATH/css $DEPLOYPATH/js $DEPLOYPATH/img
    - /bin/cp -r vis/dist $DEPLOYPATH
    - /bin/cp -r static/* $DEPLOYPATH
    - cd static; /bin/cp -r * $DEPLOYPATH; cd ..;
    - /bin/cp -rn node_modules $DEPLOYPATH